
// -----

def SPIRV_NVCreateTensorViewOp : SPIRV_NvVendorOp<"CreateTensorView", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVCreateTensorLayoutOp : SPIRV_NvVendorOp<"CreateTensorLayout", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorLayoutSetBlockSizeOp : SPIRV_NvVendorOp<"TensorLayoutSetBlockSize", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorLayoutSetDimensionOp : SPIRV_NvVendorOp<"TensorLayoutSetDimension", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorLayoutSetClampValueOp : SPIRV_NvVendorOp<"TensorLayoutSetClampValue", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorLayoutSetStrideOp : SPIRV_NvVendorOp<"TensorLayoutSetStride", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorLayoutSliceOp : SPIRV_NvVendorOp<"TensorLayoutSlice", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorViewSetClipOp : SPIRV_NvVendorOp<"TensorViewSetClip", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorViewSetDimensionOp : SPIRV_NvVendorOp<"TensorViewSetDimension", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

def SPIRV_NVTensorViewSetStrideOp : SPIRV_NvVendorOp<"TensorViewSetStride", []> {
  let summary = "Reserved.";

  let description = [{


    <!-- End of AutoGen section -->

    ```
    [TODO]
    ```

    #### Example:

    ```mlir
    [TODO]
    ```
  }];

  let availability = [
    MinVersion<SPIRV_V_1_0>,
    MaxVersion<SPIRV_V_1_6>,
    Extension<[]>,
    Capability<[SPIRV_C_TensorAddressingNV]>
  ];
}

// -----

